-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE "diary" (
	"pk" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "diary_pk_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"content" text,
	"date" timestamp
);
--> statement-breakpoint
ALTER TABLE "diary" ENABLE ROW LEVEL SECURITY;
*/