name: Wake up periodically
on:
  schedule:
    - cron: "0 0 */5 * *"  # 매 5일마다 실행, 자정에 실행
  workflow_dispatch:  # 수동 실행용
jobs:
  send_request:
    runs-on: ubuntu-latest
    env:
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
    steps:
      - name: Send request
        run: |
          curl 'https://hydhqrohhpgwybhlhwun.supabase.co/rest/v1/diary?select=pk' \
          -H "apikey: $SUPABASE_KEY" \
          -H "Authorization: Bearer $SUPABASE_KEY"